services:
    benchmark.normalizer.user:
        class: PhpBenchmarksSymfony\RestApiBundle\Normalizer\UserNormalizer
        public: false
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer }

    benchmark.normalizer.comment:
        class: PhpBenchmarksSymfony\RestApiBundle\Normalizer\CommentNormalizer
        public: false
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer }

    benchmark.normalizer.comment_type:
        class: PhpBenchmarksSymfony\RestApiBundle\Normalizer\CommentTypeNormalizer
        public: false
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer }

    benchmark.event_listener.define_locale:
        class: PhpBenchmarksSymfony\RestApiBundle\EventListener\DefineLocaleEventListener
        arguments: ['@service_container', '@translator']
        tags:
            - { name: kernel.event_listener, event: defineLocale }
